[package]
name = "stochest-macros"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords = ["stochastic", "testing", "hypothetis"]
categories = ["development-tools::testing"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]

[lints]
workspace = true
